### ISSUE TITLE
LDAP-Plugin Omeka 2.1.2

### ISSUE THREAD

**Issue by ghost** [BGSU-LITS/LDAP-Plugin#5]
Hello,

I have Omeka 2.1.2. I need to allow only certain people to access some exhibitions. I thought of the LDAP authentication and found the LDAP Plugin. But the plugin only works for OMEKA 2.2.2+. What can I do? Is there any plugin that works with OMEKA 2.1.2? Or any other plugin that might give me this authentication flexibility?

Please advise,
Best Regards.
Layale.

**Comment by daveWid** [comment]
If you pull down version 0.3.1 it will work with 2.0+

https://github.com/BGSU-LITS/LDAP-Plugin/tree/0.3.1

**Comment by ghost** [comment]
Hello,

Thank you so much for your prompt response. I downloaded version 0.3.1 as you proposed and placed the folder in the Plugins folder of Omeka 2.1.2. When I opened the Plugins page, I got "LDAP-Plugin-0.3.1" This is not a valid plugin.

What is that? Any suggestions?

Many thanks again,
Regards.

**Comment by daveWid** [comment]
I haven't worked with Omeka in quite a while now, maybe it was a clone problem??

You might want to try downling release instead of cloning the repo.

https://github.com/BGSU-LITS/LDAP-Plugin/releases

**Comment by zensense** [comment]
Hi, this might be a namespace problem.

Try renaming the plugin folder to "Ldap".

**Comment by ghost** [comment]
Hello,

You were totally right. After renaming the folder to Ldap it worked.

What configurations should I use?

Thanks.

**Comment by zensense** [comment]
No problem! 

Honestly, I'm not sure about the configuration, since I'm only researching for my own plugin. (Shibboleth auth instead of LDAP). 

The suggestion in the README.md file suggests looking at <a href="http://framework.zend.com/manual/1.12/en/zend.auth.adapter.ldap.html#zend.auth.adapter.ldap.server-options" target="_blank">the Zend docs</a> for configuration options.

The first options will be the most important, hostname, whether or not you're using SSL, etc. If you're unsure about these basic options, talk to your DevOps/SysAdmin.

**Comment by kloor** [comment]
I've released a new plugin that provides both CAS and LDAP authentication for Omeka:
https://github.com/BGSU-LITS/omeka-plugin-CentralAuth

@lbassil, you may want to look into that plugin, as it has more documentation and examples for LDAP. To configure one of these plugins, you will at least need to know the hostname and port of your LDAP server, as well as the base DN and account filter format. Even though both plugins are currently set to only work with Omeka 2.2.2, they are only untested in earlier versions. If you change the plugin.ini to set omeka_minimum_version to your version of Omeka, you will be able to install the plugin. If the plugin works, let me know.

@zensense, I'm not certain how similar Shibboleth is to CAS, but you may also want to look at the new plugin. I've also left room in that plugin to support other forms of Single Sign On besides CAS.

**Comment by gauburtin** [comment]
@kloor, i tested CentralAuth with CAS deactivated. Whereas i provided same config info as in LDAP plugin, the authentication process did not work; Is there any way to trace logs of the process between Omeka, CentralAuth and LDAP ? I won't use  LDAP plugin because it only uses one way to authenticate (LDAP OR OMEKA), whereas CentralAuth can let Omeka uses its own users passwords

**Comment by kloor** [comment]
@gauburtin, the error message handling is less than ideal in the CentralAuth plugin at this point. LDAP errors will be displayed only if LDAP is required. But, that will block you from logging into Omeka while LDAP is not working. You would either have to keep an administrative login in another browser, or edit the configuration options directly in the database to log in again.

I've added a ticket to CentralAuth to improve error reporting for LDAP, but I wont be able to get around to working on it immediately: https://github.com/BGSU-LITS/omeka-plugin-CentralAuth/issues/2

In the code, the errors from logging into LDAP would be obtained on line 149 of controllers/UsersController.php: `$messages = $result->getMessages();`

If you could provide your LDAP configuration values, outside of username/password, I could see if there are any issues I'm aware of.

**Comment by gauburtin** [comment]
@kloor  Hi John,
Your CentralAuth update is functional but i had to change the Account Canonical Form option to 1 (previously 2). 

With the LDPA account form, you may use this option : 
                                1. DN: CN=Alice Baker,CN=Users,DC=example,DC=edu  
Error reporting is very useful.
Thanks again,
Gautier
